apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  order.datasource.url: jdbc:postgresql://postgres:5432/orderdb
  inventory.datasource.url: jdbc:postgresql://postgres:5432/inventorydb
  datasource.username: appuser
  datasource.password: app_pass
  security.jwt.secret: dev-jwt-signing-secret-change-me-32chars-minimum

